### ISSUE TITLE
How to get it working?

### ISSUE THREAD

**Issue by ManvendraSK** [mattlewis92/htmlhint-loader#1]
I have this setup. 

## webpack.config.js
```js

var path = require("path");

// console.log(path.join(__dirname, 'src'));
// console.log(path.resolve(__dirname, "src"));

module.exports = {
	entry: {
		app : "./entry.js", 
		src : "./src/a.js"
	} ,
	output: {
		path: path.join(__dirname, "out"),
		filename: "[name].js"
	},
	module: {
		preLoaders: [
			{
	           test: /\.jsx?$/,
	           exclude: /node_modules/,
	           loader: 'jshint-loader',
       		},
       		{test: /\.html/, loader: 'htmlhint?{tagname-lowercase: true}', exclude: /node_modules/}
		]
	},
	htmlhint: {
    	    configFile: './.htmlhintrc'
	}
};
```

## test.html
```html
<!DOCTYPE html>
<html>
<head>
	<title>Title is here</title>
</head>
<body>
<DIV ></DIV>

<img src="http://kevinpelgrims.com/blog/files/images/2015/05/gradle_icon.png" />
</body>
</html>
```

## .htmlhintrc
```json
{
  "tagname-lowercase": true,
  "attr-lowercase": true,
  "attr-value-double-quotes": true
}
```

It should have shown error for capitalized div elements, but it's not doing so.

Could you please tell me some points or hints?

**Comment by mattlewis92** [comment]
As you're not using the html loader I'm assuming you're not loading the html file in your source so webpack doesn't know it exists. You need to install and configure the [html loader](https://github.com/webpack/html-loader) then in `./entry.js` put `require('test.html')`

**Comment by ManvendraSK** [comment]
Oh, I got your point. Thanks. But it's working only when I setup the loader using 
```js
loaders: [
	      {
	        test: /\.html$/,
	        loader: "html"
	      }
	    ]
```
and requiring the exact file `require('html!./test.html');` inside `entry.js`. Is there any other way to watch for all the directories, and automatically lint all html files? Something like `require('html!./src');`.

**Comment by mattlewis92** [comment]
You can do that with webpack: https://webpack.github.io/docs/context.html

```
function requireAll(requireContext) {
  return requireContext.keys().map(requireContext);
}
requireAll(require.context("./src", true, /^\.\/.*\.html$/));
```

Although if you don't intend to bundle your templates with your JS you might be better off using [gulp](https://www.npmjs.com/package/gulp-htmlhint)

**Comment by ManvendraSK** [comment]
Ohk.. Thanks a lot. You seems to be a champ of Webpack. I just started learning it 2 days back. Why don't you write a book on it?

**Comment by mattlewis92** [comment]
Far smarter people out there have done a [much better job](https://leanpub.com/survivejs-webpack) that I could do 😄 

If you're just getting started here are a few resources that might help:
https://github.com/petehunt/webpack-howto
https://webpack.github.io/docs/list-of-tutorials.html
https://egghead.io/courses/using-webpack-for-production-javascript-applications

**Comment by ManvendraSK** [comment]
:laughing: You are also expert IMHO! Yes I looked into that Survive.js link during my weekend. Thanks for sharing the details.
