### ISSUE TITLE
Error when report is generated

### ISSUE THREAD

**Issue by bjaguilar** [mattlewis92/htmlhint-loader#10]
Hi, I got the next while webpack generates a report of a HTML which violated some htmlhint rules:

> ERROR in   Error: Child compilation failed:
  Module build failed: TypeError: formatter.on is not a function
>   - checkstyle.js:8 Object.checkstyleFormatter [as formatter]
>     [angular-hello-world]/[htmlhint]/bin/formatters/checkstyle.js:8:15
>   
>   - index.js:98 lint
>     [angular-hello-world]/[htmlhint-loader]/index.js:98:47
>   
>   - index.js:164 fs.readFile
>     [angular-hello-world]/[htmlhint-loader]/index.js:164:13
>   
>   
>   - TypeError: formatter.on is not a function
>   
>   - compiler.js:76 
>     [angular-hello-world]/[html-webpack-plugin]/lib/compiler.js:76:16
>   
>   - Compiler.js:291 Compiler.<anonymous>
>     [angular-hello-world]/[webpack]/lib/Compiler.js:291:10
>   
>   - Compiler.js:494 
>     [angular-hello-world]/[webpack]/lib/Compiler.js:494:13
>   
>   - Tapable.js:138 next
>     [angular-hello-world]/[tapable]/lib/Tapable.js:138:11
>   
>   - CachePlugin.js:62 Compiler.<anonymous>
>     [angular-hello-world]/[webpack]/lib/CachePlugin.js:62:5
>   
>   - Tapable.js:142 Compiler.applyPluginsAsyncSeries
>     [angular-hello-world]/[tapable]/lib/Tapable.js:142:13
>   
>   - Compiler.js:491 
>     [angular-hello-world]/[webpack]/lib/Compiler.js:491:10
>   
>   - Tapable.js:131 Compilation.applyPluginsAsyncSeries
>     [angular-hello-world]/[tapable]/lib/Tapable.js:131:46
>   
>   - Compilation.js:645 self.applyPluginsAsync.err
>     [angular-hello-world]/[webpack]/lib/Compilation.js:645:19
>   
>   - Tapable.js:131 Compilation.applyPluginsAsyncSeries
>     [angular-hello-world]/[tapable]/lib/Tapable.js:131:46
>   
>   - Compilation.js:636 self.applyPluginsAsync.err
>     [angular-hello-world]/[webpack]/lib/Compilation.js:636:11
>   
>   - Tapable.js:131 Compilation.applyPluginsAsyncSeries
>     [angular-hello-world]/[tapable]/lib/Tapable.js:131:46
>   
>   - Compilation.js:631 self.applyPluginsAsync.err
>     [angular-hello-world]/[webpack]/lib/Compilation.js:631:10
>   
>   - Tapable.js:131 Compilation.applyPluginsAsyncSeries
>     [angular-hello-world]/[tapable]/lib/Tapable.js:131:46
>   
>   - Compilation.js:627 sealPart2
>     [angular-hello-world]/[webpack]/lib/Compilation.js:627:9
>   
>   - Tapable.js:131 Compilation.applyPluginsAsyncSeries
>     [angular-hello-world]/[tapable]/lib/Tapable.js:131:46
>   
>   - Compilation.js:575 Compilation.seal
>     [angular-hello-world]/[webpack]/lib/Compilation.js:575:8
>   
>   - Compiler.js:488 
>     [angular-hello-world]/[webpack]/lib/Compiler.js:488:16
>   
>   - Tapable.js:225 
>     [angular-hello-world]/[tapable]/lib/Tapable.js:225:11
>   
>   - Compilation.js:477 _addModuleChain
>     [angular-hello-world]/[webpack]/lib/Compilation.js:477:11
>   
>   - Compilation.js:448 processModuleDependencies.err
>     [angular-hello-world]/[webpack]/lib/Compilation.js:448:13
>   
>   - next_tick.js:73 _combinedTickCallback
>     internal/process/next_tick.js:73:7
>   
>   - next_tick.js:104 process._tickCallback
>     internal/process/next_tick.js:104:9
>   
> 
> Child html-webpack-plugin for "index.html":
>     [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] ./~/html-webpack-plugin/lib/loader.js!./src/index.html 616 bytes {0} [built] [failed] [1 error]
>     
>     ERROR in ./~/html-webpack-plugin/lib/loader.js!./src/index.html
>     Module build failed: TypeError: formatter.on is not a function
>         at Object.checkstyleFormatter [as formatter] (/media/DATA/Programming/AngularJS/AngularJS 4/angular-hello-world/node_modules/htmlhint/bin/formatters/checkstyle.js:8:15)
>         at lint (/media/DATA/Programming/AngularJS/AngularJS 4/angular-hello-world/node_modules/htmlhint-loader/index.js:98:47)
>         at fs.readFile (/media/DATA/Programming/AngularJS/AngularJS 4/angular-hello-world/node_modules/htmlhint-loader/index.js:164:13)
>         at tryToString (fs.js:449:3)
>         at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)

The following is a extract of my `webpack.config.js`
```
"rules": [
      {
        "enforce": 'pre',
        "test": /\.html$/,
        "loader": 'htmlhint-loader',
        "exclude": /node_modules/,
        "options": {
          "configFile": '.htmlhintrc.json',
          "failOnError": true,
          "failOnWarning": false,
          "outputReport": {
            "filePath": 'checkstyle-[name].xml',
            "formatter": require('htmlhint/bin/formatters/checkstyle')
          }
        }
     },
  // . . . 
```
I am using 
 - htmlhint-loader 1.3.0 
 - htmlhint 0.9.13
 - webpack 2.6.1

**Comment by mattlewis92** [comment]
It seems like there is an error with the docs here, there isn't actually any support for using htmlhints formatters with this loader. Htmlhints formatters only output the reports via console.log and there is no programmatic way of getting the report result as a string, so you have to do the formatting yourself: https://github.com/yaniswang/HTMLHint/blob/master/bin/formatters/checkstyle.js#L46-L49
