### ISSUE TITLE
simpler custom rules import

### ISSUE THREAD

**Issue by Ellomend** [mattlewis92/htmlhint-loader#12]
is it possible to make creating multiple custom rules simpler.
I want to make about 50-100 rules to my project, and creating those files and adding reference going to be hard task

**Comment by mattlewis92** [comment]
You could use the [rulesDir option](https://github.com/mattlewis92/htmlhint-loader#rulesdir) to auto import a directory of rules.

**Comment by Ellomend** [comment]
i have problem with that, 
if i mention rule in rulesDir option it works, but if i just create file it doesnt seems to work.
is it neccessary for rule to be mentioned in options to work or im missing something ?

**Comment by mattlewis92** [comment]
Sorry I'm not sure I follow you, could you share some code or something that reproduces your problem? Thanks!

**Comment by Ellomend** [comment]
i have options 

```
      {
        loader: 'htmlhint-loader',
        exclude: /node_modules/,
        options: {
          rulesDir: 'rules/',
          'my-new-rule': 'this is pass to the rule (option)'
        }
      }


```
and in in rule folder i have rules:
/myNewRule.js
/testRule.js

myNewRule works, testRule doesnt.
if i add 
`'test-rule': 'this is pass to the rule (option)'`
it will work.

**Comment by Ellomend** [comment]
i read docs wrong,
added my rule to .htmlhintrc and it worked
