### ISSUE TITLE
configFile option ignored

### ISSUE THREAD

**Issue by schmod** [mattlewis92/htmlhint-loader#4]
Hi,

It doesn't seem that the `configFile` option described in the documentation actually does anything.  

Skimming through the source code, it appears that this parameter gets handed directly to htmlhint, which doesn't actually do anything with it.

**Comment by mattlewis92** [comment]
The config file is read here: https://github.com/mattlewis92/htmlhint-loader/blob/master/index.js#L113

and there is a test verifying it works here: https://github.com/mattlewis92/htmlhint-loader/blob/master/test/test.spec.js#L97-L116
