### ISSUE TITLE
Reading configFile throws an error

### ISSUE THREAD

**Issue by andy01pr** [mattlewis92/htmlhint-loader#6]
When reading the `configFile` throws an error when parsing the json content. The method `fs.readFile` returns a `Buffer` object instead of a string.
https://github.com/mattlewis92/htmlhint-loader/blob/master/index.js#L134

**Comment by mattlewis92** [comment]
I think the `Buffer` issue is a red herring, JSON.parse should implicitly call the Buffer's toString method when parsing. There [are tests](https://github.com/mattlewis92/htmlhint-loader/blob/master/test/test.spec.js#L127-L146) that verify this works. Please verify the file exists in the correct path and is definitely valid JSON. If you're still stuck please can you make a repo that reproduces your problem and I'd be more than happy to dig in more to see what's going on. Thanks! 😄

**Comment by andy01pr** [comment]
The problem was the encoding in the file that I was using. The encoding was `UTF-8-BOM` and that caused the JSON.parse to throw the error.

**Comment by mattlewis92** [comment]
Can you share the file with me that I can use as a test case?

**Comment by andy01pr** [comment]
The file was created using Visual Studio 2015.

[htmlhint.zip](https://github.com/mattlewis92/htmlhint-loader/files/698898/htmlhint.zip)

**Comment by mattlewis92** [comment]
Perfect, thanks for that! Should be fixed now in 1.1.1 😃
