### ISSUE TITLE
Suggestion: improve handling of configFile paths

### ISSUE THREAD

**Issue by rondonjon** [mattlewis92/htmlhint-loader#9]
Before using htmllint-loader, I was able to execute my webpack build from various directories (`cwd`); now, I am forced to do so from one specific location, because otherwise the config file cannot be found. The reason is that every given configFile path is processed by this line:

`const configFilePath = path.join(process.cwd(), options.configFile);`

I would suggest two changes to further improve the code:

(1.) Allow absolute paths to be passed in. If a path is already absolute, do not join the cwd:

```
let configFilePath = options.configFile;
if (!path.isAbsolute(configFilePath)) {
  configFilePath = path.join(process.cwd(), configFilePath);
}
```

(2.) Throw an error if a `configFile` was specified and cannot be located. Currently, this would be silently ignored!

**Comment by mattlewis92** [comment]
Make sense, released as 1.3.0 🎉
